### ISSUE TITLE
retries keep adding to the query

### ISSUE THREAD

**Issue by purplecabbage** [adobe/aio-cli-plugin-app#504]
it looks like a non-200 response (400 in this case) results in a retry up to 3 times. with every retry, ?overwrite=true is appended to the request which ends up in ?overwrite=true?overwrite=true?overwrite=true

```
2021-12-14T20:11:56.867Z needle Making request adobe/aio-lib-runtime#1 {
  localAddress: undefined,
  lookup: undefined,
  rejectUnauthorized: true,
  agent: false,
  protocol: 'https:',
  host: 'adobeioruntime.net',
  port: 443,
  path: '/api/v1/namespaces/---/actions/----0.0.1/id-lookup-stage?overwrite=true',
  method: 'put',
...
2021-12-14T20:11:57.264Z needle Got response 400 {
  'content-length': '88',
  'content-type': 'application/json',
...
2021-12-14T20:11:57.614Z needle Making request adobe/aio-lib-runtime#1 {
  localAddress: undefined,
  lookup: undefined,
  rejectUnauthorized: true,
  agent: false,
  protocol: 'https:',
  host: 'adobeioruntime.net',
  port: 443,
  path: '/api/v1/namespaces/---/actions/----0.0.1/id-lookup-stage?overwrite=true?overwrite=true',
  method: 'put',
...
2021-12-14T20:11:57.922Z needle Got response 400 {
  'content-length': '152',
  'content-type': 'application/json',
...
2021-12-14T20:11:58.356Z needle Making request adobe/aio-lib-runtime#1 {
  localAddress: undefined,
  lookup: undefined,
  rejectUnauthorized: true,
  agent: false,
  protocol: 'https:',
  host: 'adobeioruntime.net',
  port: 443,
  path: '/api/v1/namespaces/---/actions/----0.0.1/id-lookup-stage?overwrite=true?overwrite=true?overwrite=true',
  method: 'put',
...
2021-12-14T20:11:58.715Z needle Got response 400 {
  'content-length': '167',
  'content-type': 'application/json',
```

Here is a stack trace:

```
✖ Deploying actions for 'application'
2021-12-14T20:11:58.720Z @adobe/aio-cli-plugin-app:error OpenWhiskError: PUT https://adobeioruntime.net/api/v1/namespaces/***/actions/***-0.0.1/id-lookup-stage?overwrite=true?overwrite=true?overwrite=true Returned HTTP 400 (Bad Request) --> "The query parameter 'overwrite' was malformed:
'true?overwrite=true?overwrite=true' is not a valid Boolean value"
    at Client.handleErrors (/Users/****/.nvm/versions/node/v14.17.6/lib/node_modules/@adobe/aio-cli/node_modules/openwhisk/lib/client.js:266:11)
    at /Users/***/.nvm/versions/node/v14.17.6/lib/node_modules/@adobe/aio-cli/node_modules/openwhisk/lib/client.js:189:26
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async deployPackage (/Users/***/.nvm/versions/node/v14.17.6/lib/node_modules/@adobe/aio-cli/node_modules/@adobe/aio-lib-runtime/src/utils.js:1504:5)
    at async Object.syncProject (/Users/***/.nvm/versions/node/v14.17.6/lib/node_modules/@adobe/aio-cli/node_modules/@adobe/aio-lib-runtime/src/utils.js:1591:3)
    at async deployWsk (/Users/***/.nvm/versions/node/v14.17.6/lib/node_modules/@adobe/aio-cli/node_modules/@adobe/aio-lib-runtime/src/deploy-actions.js:216:3)
    at async Object.deployActions (/Users/***/.nvm/versions/node/v14.17.6/lib/node_modules/@adobe/aio-cli/node_modules/@adobe/aio-lib-runtime/src/deploy-actions.js:104:28)
    at async Deploy.deploySingleConfig (/Users/***/.nvm/versions/node/v14.17.6/lib/node_modules/@adobe/aio-cli/node_modules/@adobe/aio-cli-plugin-app/src/commands/app/deploy.js:123:41)
    at async Deploy.run (/Users/***/.nvm/versions/node/v14.17.6/lib/node_modules/@adobe/aio-cli/node_modules/@adobe/aio-cli-plugin-app/src/commands/app/deploy.js:65:9)
Error: PUT https://adobeioruntime.net/api/v1/namespaces/***/actions/***-0.0.1/id-lookup-stage?overwrite=true?overwrite=true?overwrite=true Returned HTTP 400 (Bad Request) --> "The query parameter 'overwrite' was malformed:
'true?overwrite=true?overwrite=true' is not a valid Boolean value"
    at Object.error (/Users/***/.nvm/versions/node/v14.17.6/lib/node_modules/@adobe/aio-cli/node_modules/@oclif/errors/lib/index.js:26:15)
    at Deploy.error (/Users/***/.nvm/versions/node/v14.17.6/lib/node_modules/@adobe/aio-cli/node_modules/@oclif/command/lib/command.js:60:23)
    at Deploy.handleError (/Users/***/.nvm/versions/node/v14.17.6/lib/node_modules/@adobe/aio-cli/node_modules/@adobe/aio-cli-plugin-app/src/BaseCommand.js:42:10)
    at Deploy.catch (/Users/***/.nvm/versions/node/v14.17.6/lib/node_modules/@adobe/aio-cli/node_modules/@adobe/aio-cli-plugin-app/src/BaseCommand.js:33:10)
    at Deploy._run (/Users/***/.nvm/versions/node/v14.17.6/lib/node_modules/@adobe/aio-cli/node_modules/@oclif/command/lib/command.js:47:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Config.runCommand (/Users/***/.nvm/versions/node/v14.17.6/lib/node_modules/@adobe/aio-cli/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/Users/***/.nvm/versions/node/v14.17.6/lib/node_modules/@adobe/aio-cli/node_modules/@oclif/command/lib/main.js:27:9)
    at async Main._run (/Users/***/.nvm/versions/node/v14.17.6/lib/node_modules/@adobe/aio-cli/node_modules/@oclif/command/lib/command.js:43:20)
```

**Comment by shazron** [comment]
Fix merged in https://github.com/apache/openwhisk-client-js/pull/231 and slated for https://www.npmjs.com/package/openwhisk version 3.21.6 which requires an Apache Openwhisk PMC vote before it can be released

**Comment by shazron** [comment]
`openwhisk@3.21.6` has been released: https://www.npmjs.com/package/openwhisk
