### ISSUE TITLE
wskdebug: optional dependency `cpu-features` install error

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli-plugin-app#549]
## Dependency Tree

```
$ npm ls cpu-features
└─┬ @openwhisk/wskdebug@1.4.0
  └─┬ dockerode@3.3.1
    └─┬ docker-modem@3.0.3
      └─┬ ssh2@1.10.0
        └── UNMET OPTIONAL DEPENDENCY cpu-features@0.0.4
```

## Error

```
> cpu-features@0.0.4 install /Users/shaz/Desktop/tmp/test-1/node_modules/cpu-features
> node buildcheck.js > buildcheck.gypi && node-gyp rebuild

  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_aarch64_linux_or_android.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_arm_linux_or_android.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_mips_linux_or_android.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_ppc_linux.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_x86_freebsd.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_x86_linux_or_android.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_x86_macos.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_x86_windows.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/filesystem.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/stack_line_reader.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/string_view.o
  LIBTOOL-STATIC Release/cpu_features.a
env: python: No such file or directory
make: *** [Release/cpu_features.a] Error 127
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/shaz/.nvm/versions/node/v14.19.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Darwin 21.4.0
gyp ERR! command "/Users/shaz/.nvm/versions/node/v14.19.2/bin/node" "/Users/shaz/.nvm/versions/node/v14.19.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/shaz/Desktop/tmp/test-1/node_modules/cpu-features
gyp ERR! node -v v14.19.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

## Repro Steps

1. Install an app via `aio app init`
2. Choose `Standalone Application`
3. Uncheck `Events` and `Web Assets`

## Investigation

`python` v2 is no longer installed with macOS Monterey. 

## Workaround

To get rid of this error, users have to install python v2 manually: https://www.python.org/downloads/release/python-2713/

## Fix

This has to be fixed via `wskdebug`, perhaps there is an update in their dependencies that will not require python 2.

**Comment by shazron** [comment]
Note: this is an optional dependency of ssh2, and doesn't affect wskdebug functionality AFAIK

**Comment by shazron** [comment]
Related: https://github.com/apache/openwhisk-wskdebug/issues/113
